//this code is generated by perplexity ai, using "GeeksforGeeks C++ Radix Sort Implementation" as reference
//i will learn from this code and improve it later
//https://www.geeksforgeeks.org/cpp/cpp-program-for-radix-sort/
#pragma once
#include <vector>
#include <algorithm>  // for std::max_element

void countSort(std::vector<int>& vec, int exp);
void radixSort(std::vector<int>& vec);